### ISSUE TITLE
Autostart in Kiosk Mode

### ISSUE THREAD

**Issue by notcallumfisher** [r10s/silverjuke#104]
Hey, can you please help me autostart Silverjuke in Ubuntu in Kiosk Mode? I didn't notice this option in any setting menu. Thank you.

**Comment by r10s** [comment]
you should be able to start with the cli switch --kiosk

**Comment by notcallumfisher** [comment]
That works perfectly. Awesome! Thank you

**Comment by r10s** [comment]
you're welcome!
