### ISSUE TITLE
xine: We do not receive live data for fading, autovol, visualisations [Linux]

### ISSUE THREAD

**Issue by r10s** [r10s/silverjuke#11]
Currently, we do not receive live data when using _xine_ as the playback engine; eg. the spectrum analyzer and the oscilloscope only show a null-data, automatic volume, fading don't work.

Maybe we will switch from _xine_ to _gstreamer_ completely.

This affects Silverjuke on Linux only.

**Comment by timo18146** [comment]
Hi Bjoern,
did you already decide to stay at libxine or switch to gstreamer? I really would appreciate to see fade in/out working under linux as most hard issues are resolved now that prevent silverjuke from being used in production environment - even with woodenbox v3.0 and scripting.

Gruß Timo

**Comment by r10s** [comment]
Hi Timo,

no, there is no decision yet. However, of course, I also want this stuff to work.

**Comment by r10s** [comment]
We use GStreamer now, visualisations do work and fading and the rest should work soon, too.
