### ISSUE TITLE
Editing a track while being played queues same track again

### ISSUE THREAD

**Issue by JukeFan** [r10s/silverjuke#13]
Symptom:
SilverJuke is playing a track (in auto play mode).
The currently playing track gets edited and saved.
Silverjuke plays after this track a new track.
After finishing the new track, the edited track gets played again.

OS: Windows 7 Pro
SilverJuke: 3.04

**Comment by r10s** [comment]
Solved, see http://forum.silverjuke.net/viewtopic.php?f=7&t=4127&p=16345#p16331

**Comment by JukeFan** [comment]
Hi r10s,

The issue above has nothing to do with the one from the forum.
As far as I know, is the problem still there (in SJ 3.04)

King regards, JukeFan

**Comment by r10s** [comment]
Okay, we will check this again.

**Comment by r10s** [comment]
More common way to reproduce this, independingly of AutoPlay etc.:
- If a tracks was played completely, there is a little checkmark in the display left of the title (to indicate "Already played")
- If you edit the track the track using the build-in track editor, this checkmark will disappear
- Under some circumstances then, of course, the edited track gets played again (eg. if "Shuffle" is on)

But: Is this a bug? Or wanted behaviour?

**Comment by JukeFan** [comment]
Hi Björn,

Thank you for looking into the matter.
I wasn't aware of the existence of such flag.

In answering your question "Is this a bug? Or wanted behavior?":
To me this is unwanted behavior, but that's my humble opinion.

Let's look at the matter from the opposite side.
In case the check-mark was not set before an edit:
Would you want to have that check-mark to be set to already played after editing the track?
I tend to say no.
I think the check-mark should be left as it is/was before the edit took place.

Remark: 
If the track is being edited **while being played**, the same thing happens, the track will be played again. 
In this situation it looks like that checker is set while being played (and cleared by the edit action).

Shouldn't that check-mark be set directly after finishing the played (and perhaps edited) track instead of setting it while being played and/or edited?

**Comment by JukeFan** [comment]
Wrong butto pressed.

**Comment by r10s** [comment]
Fixed. Wrong buttons pressed on keyboard before to create this bug ;-)

**Comment by r10s** [comment]
You're welcome!
