### ISSUE TITLE
Purpose of insert-header files?

### ISSUE THREAD

**Issue by r10s** [r10s/silverjuke#17]
What are the files `po/en@boldquot.insert-header` and `po/en@quot.insert-header` for?

- They are deleted my a `make clean` but also tracked by Git - so after cleaning, the Git repositiory says tracked files are deleted

- The files can be recreated by `cd po; make en@boldquot.insert-header; make en@quot.insert-header`
	
Maybe, the files can be removed from the repository, however, I'm not sure if any tools just relies on its existance. Any Ideas?

**Comment by r10s** [comment]
Corresponding commit: https://github.com/r10s/silverjuke/commit/df395962fd347d32a096f4dcca26764ab82d9953

**Comment by toddy15** [comment]
This can be closed, the files are regenerated on the fly when calling "make update-po". They have been added to the repository accidentally.
