### ISSUE TITLE
Defaults of skins and keyboard search paths may be wrong

### ISSUE THREAD

**Issue by r10s** [r10s/silverjuke#19]
while `make install` saves eg. skins to `/usr/local/share/silverjuke/skins/`, Silverjuke may try to read them from `/usr/share/silverjuke/skins` ... we should forward the paths used by make to a header file read during compilation time.

**Comment by r10s** [comment]
forwarding the paths to a header is not as simple as it sounds. Instead, we rely on wxStandardPaths::Get().GetDataDir() now and hope the best.

**Comment by toddy15** [comment]
There's probably a better solution: define the data directory of the package during compilation, so that there's a string constant available. I've implemented this solution, feel free to comment.

**Comment by r10s** [comment]
Perfect, thanks!
