### ISSUE TITLE
Mac version crashes (v2.74) when clicking a song and dragging it up or down [Mac]

### ISSUE THREAD

**Issue by IjzerenHein** [r10s/silverjuke#22]
When I click a song from the list (click it and hold the mouse button down) and move the mouse up or down, the current Mac version crashes immediately. This happens on Mac OSX El Capitan (I haven't tested on older mac osx's) and is easy to reproduce.
I've included a short video to show the problem.

![silverjuke](https://github-cloud.s3.amazonaws.com/assets/6184593/10565701/a97ecf42-75d7-11e5-98be-cc2864b82db3.gif)

Crash dump here:
https://gist.github.com/IjzerenHein/75b8d16f418b77bfc9ec

**Comment by r10s** [comment]
Thank you very much for your report. Currently, it is unclear, what will happen to the mac version, however, we hope that we can offer an updated Silverjuke 15.x these weeks.

**Comment by IjzerenHein** [comment]
That would be awesome! If there is anything I can do help test or debug let me know.
Cheers

**Comment by r10s** [comment]
Thank you for your offer, we have your e-mail-address and we will contact you if needed.

**Comment by IjzerenHein** [comment]
Hey, I'd also be very happy fixing the issue in the Mac version myself. I have a lot of programming experience also in Objective-C. I would really love to see this problem resolved. From the looks of it, it seems that a drag gesture is being triggered, which is not handled correctly. If I'd have access to the code, I'd make the changes myself and push it back to you :)

**Comment by r10s** [comment]
Thank you for your offer, but the Mac part is not open source. Moreover, it is very likely that the bug is already fixed with 15.8, however, at the moment, I do not have a mac here to really test it ... If we run into bigger problems, however, I would like to contact you.

**Comment by IjzerenHein** [comment]
Sure no problem, let me know if I can help.
Cheers

**Comment by r10s** [comment]
Fixed in the upcoming Mac version.

**Comment by IjzerenHein** [comment]
Awesome, thanks so much!!
