### ISSUE TITLE
bass 2.2 erforerlich

### ISSUE THREAD

**Issue by skietz** [r10s/silverjuke#50]
beim starten von silverjuke kommt eine Fehlermeldung, dass die Bass 2.2 erfordert wird. woher bekomme ich das?

**Comment by r10s** [comment]
Please write your posts in english; for german use the forum at http://forum.silverjuke.net/viewforum.php?f=3 

BASS is available at http://www.un4seen.com

However, the BASS library normally comes together with Silverjuke in the correct version. The currently used version is 2.4. It seems as if you have tried to install different Silverjuke versions into the same directory without uninstalling them first.
To fix this, 
- make a Backup 
- uninstall all Silverjuke versions
- install Silverjuke again
If you want to use different Silverjuke versions at the same time, install them to different directories.

**Comment by skietz** [comment]
thank you
