### ISSUE TITLE
tracks.timesmodified, tracks.timesplayed, tracks.lastplayed not written to database after played some tracks

### ISSUE THREAD

**Issue by timo18146** [r10s/silverjuke#56]
reproducable at least on ubuntu whily version 15.10.1
no general writable sqlite-database problem - ratings are written.

**Comment by r10s** [comment]
thank you for the report, we will check this.

**Comment by r10s** [comment]
okay, we've checked this: the used xine player simply does not call SaveGatheredInfo(); this also results in player.onPlaybackDone (scripting function) being never called on Linux.
Windows and Mac is okay.
We will fix this issue soon.

**Comment by r10s** [comment]
Fixed by commit a7a41fd.
