### ISSUE TITLE
Mac version crashes after 30 seconds of using it

### ISSUE THREAD

**Issue by IjzerenHein** [r10s/silverjuke#60]
Hi,

I'm using the latest Mac version of Silverjuke (16.1.3) and found a crash which occurs very regularly. I am building a simple custom theme and found that the app crashes after 30 seconds. I've included the theme as well as one of the crash logs that I recorded.

To reproduce, load the theme, and click any of the custom buttons (e.g. "Flash", "Carnaval", etc..). Initially nothing bad happens, but when you press such a button after 30 seconds, the program crashes.
The buttons execute an empty script function. Just try pressing it continuously for 30 seconds.

![silverjuke](https://cloud.githubusercontent.com/assets/6184593/12796286/55eabae4-cabe-11e5-96bd-9c36bb2033b7.gif)

best regards,
Hein

[Silverjuke_2016-02-03-212229_IjzerenHein.crash.zip](https://github.com/r10s/silverjuke/files/116351/Silverjuke_2016-02-03-212229_IjzerenHein.crash.zip)

[flash.sjs.zip](https://github.com/r10s/silverjuke/files/116343/flash.sjs.zip)

**Comment by r10s** [comment]
Hello Hein,

again, thank you for your report, we will check this, however, these days we prepare Silverjuke for the next Ubuntu LTS release, so it may take a little time until I open my MacBook again.

In between: There is already a newer vesion of Silverjuke, 16.2.1beta, see http://forum.silverjuke.net/viewtopic.php?f=7&t=4205 

Best regards,
Björn

**Comment by IjzerenHein** [comment]
Hello Bjorn,

Thanks for the quick response and letting me know about the release status and beta, the screenshots look awesome!

If I can be of any assistance let me know.

cheers,
Hein

**Comment by r10s** [comment]
Hello again,

have you found the download above the screenshots? For future beta-versions, you can subscribe to the newsletter at http://www.silverjuke.net/en/newsletter (tick "beta").

Best regards,
Björn

**Comment by IjzerenHein** [comment]
Hi,

I just downloaded the new beta version and registered for the (beta) newsletter.
The beta version also crashes in the same manner 16.1.3 did.

cheers, Hein

**Comment by IjzerenHein** [comment]
Hi Bjorn,

Is there a location where I can download the previous Mac version (pre 16.1.x)? The current version is unfortunately unusable for me at this stage.

best regards,
Hein

**Comment by r10s** [comment]
Hi Hein,

- 16.1.x is currently available at http://www.silverjuke.net/en/download - at the bottom of the page you can also access some older versions in the "customer area"
- for older OpenSource versions, see "Code/Releases" on Github

In common, we should treat Scripting as being unstable on Mac at the moment - or do you encounter any other problems non-scripting related? 
We have a MacBook here that plays Music with Silverjuke day and night without any problems ...

Best regards,
Björn

**Comment by r10s** [comment]
We're on the way, it seems to come from the [garbage collection which is done every 30 seconds](https://github.com/r10s/silverjuke/blob/master/src/sjtools/gcalloc.h#L102) ... however, currently I have no idea, why this happens on Mac OS X only.

**Comment by IjzerenHein** [comment]
Awesome, let me know if I need to help testing anything.
Cheers!

**Comment by r10s** [comment]
Fixed, an update will be released in the next hour on http://forum.silverjuke.net/viewforum.php?f=7

Thank you very much for your help!

**Comment by IjzerenHein** [comment]
Awesome!!! Thanks so much Bjorn, much much appreciated!
