### ISSUE TITLE
Make karaoke and video files searchable in the music selection

### ISSUE THREAD

**Issue by r10s** [r10s/silverjuke#70]
It would be nice if karaoke and video files can be searched using music selection criterions.

**Comment by r10s** [comment]
We do not add this for the following reasons:

(1) This would only make sense if the information is written to the database on update.
(2) However, We cannot safely find out if a container-file contains a video without playing it - this is no acceptable regarding the performance.  Extensions may help but are not always 100% save
(3) Added karaoke file would only appear after an music-library update
(4) Point (3) could be solved, however, this would immediately raise the question why karaoke is searchable while videos are not.

The user can easily get around this issue by using the path or the file extensions as criterions (the user will know better about these as Silverjuke).

**Comment by 4jag** [comment]
@r10s My guess is that the majority of Silverjuke users are doing karaoke. I'm trying it out, and I setup a station with 85,000 karaoke files. I find that I can hit the B" button and be taken to Baa..., but if my guests are lookinging for Bruno Mars they'll need to scoll all the way to Br... --- NOPE, not gonna happen. If they could type "B" "M" and be shown only artitsts that have first name beginning with B and second/last name with B, and songs with first, second words in title, etc., then take could work. 
So, with no search, and the broken lyrics-on-2nd-monitor feature, Silverjuke is dead-on-arrival.
