### ISSUE TITLE
xp not supported on v16.5.3 despite faq

### ISSUE THREAD

**Issue by jplusc** [r10s/silverjuke#73]
launching  v16.5.3  on Windows XP Pro 32bit SP3 yields the following error message:
"the procedure entry point inet ntop cannot be located"

Apparently inet_ntop()  is a vista thing and not available for XP.

some extra info here:
http://social.msdn.microsoft.com/Forums/en-US/vcgeneral/thread/e40465f2-41b7-4243-ad33-15ae9366f4e6/
it does include a work around about falling back to  inet_ntoa()  as necessary.

Installing v15.10.1 *does* work on XP.

I am not sure when calls to  inet_ntop() were added.

If Silverjuke is no longer going to support XP, I guess that is fine, but the FAQ / system requirements should mention such, as of now it does say it will run on XP and perhaps give a link to the last version that will. 

Speaking of which, can anyone point me to the latest version between 15.10.1 and now that will work on XP?

Thanks,
J+C

**Comment by r10s** [comment]
Hi J+C,

thank you for your report.

Maybe, the dependency to inet_ntop() was added with the OpenGL libs required for the projectM visualisation.

The version just before this change was 16.1.2 which you can download here: http://www.silverjuke.net/public/download/Silverjuke-16.1.2-Setup.exe

_If_ this version works, you can also try 16.3.5 - http://www.silverjuke.net/public/download/Silverjuke-16.3.5-Setup.exe - _if_ this version works as well,  the dependency came from the UPnP-Support.

As I currently have no XP system - and probably won't have one again -, I cannot try the versions on XP myself.

Finally, I've also removed to XP-unofficially-supported hint from the FAQ.

Best regards
Björn

**Comment by jplusc** [comment]
16.3.5 does work fine on XP.

Guess that will be the last version available for XP.

Thanks much for your support.

**Comment by r10s** [comment]
Yes, so far, Silverjuke 16.3.5 is the last version working on XP without special workarounds.
